/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import javax.swing.*;
/**
 *
 * @author stevefan
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(Product product) {
        initComponents();
        displayProduct(product);
    }

    private void displayProduct(Product product){
        String productColor=product.getColor();
        colorTxtField.setText(productColor);
        
        String productModel=product.getModel();
        modelTxtField.setText(productModel);
        
        String productSerialNum=product.getSerialNum();
        serialNumTxtField.setText(productSerialNum);
        
        String productDimension=product.getDimension();
        dimensionTxtField.setText(productDimension);
        
        String productPrice=product.getPrice();
        priceTxtField.setText(productPrice);
        
        String productBrand=product.getBrand();
        brandTxtField.setText(productBrand);
        
        String productLocation=product.getLocation();
        locationTxtField.setText(productLocation);
        
        String productYear=product.getYear();
        yearTxtField.setText(productYear);
        
        String productAuto=product.getAuto();
        autoTxtField.setText(productAuto);
        
        String productSeats=product.getSeats();
        seatsTxtField.setText(productSeats);
        
        String productEngine=product.getEngine();
        engineTxtField.setText(productEngine);
        
        String productType=product.getType();
        typeTxtField.setText(productType);
        
        String productGas=product.getGas();
        gasTxtField.setText(productGas);
        
        String productUsed=product.getUsed();
        usedTxtField.setText(productUsed);
        
        String productMile=product.getMile();
        mileTxtField.setText(productMile);
        
        ImageIcon productImage=product.getImage();
        imgLabel.setIcon(productImage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        priceTxtField = new javax.swing.JTextField();
        brandTxtField = new javax.swing.JTextField();
        locationTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yearTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        seatsTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        colorTxtField = new javax.swing.JTextField();
        engineTxtField = new javax.swing.JTextField();
        modelTxtField = new javax.swing.JTextField();
        serialNumTxtField = new javax.swing.JTextField();
        typeTxtField = new javax.swing.JTextField();
        gasTxtField = new javax.swing.JTextField();
        usedTxtField = new javax.swing.JTextField();
        dimensionTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mileTxtField = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Your Favorite Car");

        jLabel8.setText("Location:");

        jLabel9.setText("Year:");

        jLabel7.setText("Brand:");

        jLabel10.setText("Auto/Mannual:");

        jLabel11.setText("Seats:");

        jLabel12.setText("Engine:");

        jLabel13.setText("Type:");

        jLabel14.setText("Gas/Elec:");

        jLabel15.setText("New/Used:");

        priceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtFieldActionPerformed(evt);
            }
        });

        locationTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Color:");

        yearTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Model:");

        autoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Serial Number:");

        seatsTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Dimension:");

        modelTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTxtFieldActionPerformed(evt);
            }
        });

        serialNumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumTxtFieldActionPerformed(evt);
            }
        });

        typeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTxtFieldActionPerformed(evt);
            }
        });

        usedTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usedTxtFieldActionPerformed(evt);
            }
        });

        dimensionTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Price:");

        jLabel16.setText("Miles:");

        mileTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel3)
                            .addComponent(jLabel16))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(engineTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                .addComponent(seatsTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(autoTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(yearTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locationTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(brandTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priceTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dimensionTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(serialNumTxtField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mileTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(usedTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gasTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeTxtField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modelTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(colorTxtField))))
                .addGap(18, 18, 18)
                .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(colorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(modelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(serialNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dimensionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(brandTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(locationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(yearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(autoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(seatsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(engineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(typeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gasTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(mileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void priceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtFieldActionPerformed

    private void locationTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTxtFieldActionPerformed

    private void yearTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTxtFieldActionPerformed

    private void autoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoTxtFieldActionPerformed

    private void seatsTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTxtFieldActionPerformed

    private void modelTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTxtFieldActionPerformed

    private void serialNumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumTxtFieldActionPerformed

    private void typeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTxtFieldActionPerformed

    private void usedTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usedTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usedTxtFieldActionPerformed

    private void dimensionTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionTxtFieldActionPerformed

    private void mileTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autoTxtField;
    private javax.swing.JTextField brandTxtField;
    private javax.swing.JTextField colorTxtField;
    private javax.swing.JTextField dimensionTxtField;
    private javax.swing.JTextField engineTxtField;
    private javax.swing.JTextField gasTxtField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationTxtField;
    private javax.swing.JTextField mileTxtField;
    private javax.swing.JTextField modelTxtField;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JTextField seatsTxtField;
    private javax.swing.JTextField serialNumTxtField;
    private javax.swing.JTextField typeTxtField;
    private javax.swing.JTextField usedTxtField;
    private javax.swing.JTextField yearTxtField;
    // End of variables declaration//GEN-END:variables
}
