/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetDietician;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Food.Dish;
import Business.Food.Diet;
import Business.Food.Material;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhythonNo1
 */
public class AccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NutritionDiningRoomEnterprise enterprise;
    private UserAccount userAccount;
    private double totalProfit = 0;
    /**
     * Creates new form AccountJPanel
     */
    public AccountJPanel(JPanel userProcessContainer, UserAccount account, NutritionDiningRoomEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        valueLabel.setText(enterprise.getName());
        populateProfitTable();
    }
    
    public void populateProfitTable() {
        DefaultTableModel model = (DefaultTableModel)profitJTable.getModel();
        model.setRowCount(0);
        
        for (Diet diet : enterprise.getFlavorDirectory().getFlavorList()) {
            if(diet.getQuantity()!=0) {
                Object[] row = new Object[4];
                row[0] = diet;
                row[1] = diet.getQuantity();
                row[2] = diet.getPrice();
                row[3] = diet.getQuantity()*diet.getPrice();
            
                model.addRow(row);
                totalProfit += diet.getQuantity()*diet.getPrice();
            }
        }
      
        for (Dish dish: enterprise.getDishDirectory().getDishList()) {
            if(dish.getQuantity()!=0 && dish.getName().equals("dish")) {
                Object[] row = new Object[4];
                row[0] = dish;
                row[1] = dish.getQuantity();
                row[2] = dish.getPrice();
                row[3] = dish.getQuantity()*dish.getPrice();
            
                model.addRow(row);
                totalProfit += dish.getQuantity()*dish.getPrice();
            }
        }
        
        for (Material material : enterprise.getMaterialDirectory().getMaterialList()) {
            if(material.getQuantity()!=0) {
                Object[] row = new Object[4];
                row[0] = material;
                row[1] = material.getQuantity();
                row[2] = material.getPrice()*(-1);
                row[3] = material.getQuantity()*material.getPrice()*(-1);
            
                model.addRow(row);
                totalProfit += material.getQuantity()*material.getPrice()*(-1);
            }
        }
        totalProfitJTextField.setText(String.format("%.2f",totalProfit));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalProfitJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profitJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalProfitJTextField.setEditable(false);
        add(totalProfitJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 314, 76, -1));

        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 371, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 142, 30));

        valueLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, 210, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Company Account");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 80, 189, 30));

        profitJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Unit Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profitJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 116, -1, 180));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel1.setText("Total Profit:   $");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 317, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pic14.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel6.setPreferredSize(new java.awt.Dimension(600, 626));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable profitJTable;
    private javax.swing.JTextField totalProfitJTextField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
