/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetDietician;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Food.Diet;
import Business.Food.Material;
import Business.Network.Network;
import Business.Organization.DieticianOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DishRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhythonNo1
 */
public class DieticianWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DieticianOrganization organization;
    private NutritionDiningRoomEnterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    /**
     * Creates new form ManagerWorkArea
     */
    public DieticianWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DieticianOrganization organization, NutritionDiningRoomEnterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = account;
        
        valueLabel.setText(enterprise.getName()+", "+organization.getName());
        styleCBox.removeAllItems();
        if(enterprise.getFlavorDirectory().getFlavorList().size() != 0) {
            populateComboBox();
        }
        
        // display dish quantity
        try{hairQuantityTxt.setText(enterprise.getDishDirectory().getDishList().get(0).getQuantity()+"");}
        catch(Exception e) {hairQuantityTxt.setText("n/a");}
        
        populateProcessRequestTable();
        //refreshreduceCO2();
    }

    public void populateComboBox() {
        styleCBox.removeAllItems();
        for(Diet hairStyle : enterprise.getFlavorDirectory().getFlavorList()) {
            styleCBox.addItem(hairStyle);
        }
    }
    public void populateMaterialTable(Diet hairStyle) {
        DefaultTableModel model = (DefaultTableModel)materialJTable.getModel();
        model.setRowCount(0);
        
        for (Material material : hairStyle.getMaterialDirectory().getMaterialList()) {
            if(material.getQuantity()!=0) {
                Object[] row = new Object[2];
                row[0] = material.getName();
                // accurate to 2 decimal places
                row[1] = String.format("%d", material.getQuantity());//%.2f
            
                model.addRow(row);
            }
        }
    }
    
    public void populateProcessRequestTable() {
        DefaultTableModel model = (DefaultTableModel)processRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            int quantity = ((DishRequest) request).getQuantity();
            row[1] = quantity;          
            String senderEnterprise = ((DishRequest) request).getSenderEnterprise() == null ? null : ((DishRequest) request).getSenderEnterprise().getName();
            row[2] = senderEnterprise;
            //row[3] =((DishRequest) request).getReceiverEnterprise().getName();
            String receiverEnterprise = ((DishRequest) request).getReceiverEnterprise() == null ? null : ((DishRequest) request).getReceiverEnterprise().getName();
            row[3] = receiverEnterprise;
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    public void refreshHairQuantity() {
        hairQuantityTxt.setText(enterprise.getDishDirectory().getDishList().get(0).getQuantity()+"");
    }
    
    public void refreshreduceCO2() {
        
//        try {enterprise.getDishDirectory().getDishList().get(0);}
//        catch (Exception e){
//            reduceCO2Txt.setText("");
//            return;
//        }
//        reduceCO2Txt.setText(String.format("%.2f", enterprise.getDishDirectory().getDishList().get(0).getQuantity()*5.00));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createJTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        materialJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        assignMaterialBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        styleCBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        processRequestJTable = new javax.swing.JTable();
        assignToMeBtn = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshSendBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hairQuantityTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accountJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        stylePriceTxt = new javax.swing.JTextField();
        createJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setBackground(new java.awt.Color(0, 51, 51));
        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 142, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 183, -1));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Create Diet:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        createJTextField.setText("<Please Type In a dish Name>");
        add(createJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 30));

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        materialJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(materialJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 273, 133));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Current Diet:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 110, 20));

        assignMaterialBtn.setText("Assign Material");
        assignMaterialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMaterialBtnActionPerformed(evt);
            }
        });
        add(assignMaterialBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Choose Diet:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        styleCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        styleCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleCBoxActionPerformed(evt);
            }
        });
        add(styleCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        processRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish", "Quantity", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(processRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 306, 96));

        assignToMeBtn.setText("Assign to me");
        assignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeBtnActionPerformed(evt);
            }
        });
        add(assignToMeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 93, -1));

        refreshSendBtn.setText("Refresh");
        refreshSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshSendBtnActionPerformed(evt);
            }
        });
        add(refreshSendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Dish Process");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));
        add(hairQuantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 51, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sample Material Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        accountJButton.setText("Account");
        accountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountJButtonActionPerformed(evt);
            }
        });
        add(accountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Price:  $");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));
        add(stylePriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 60, 30));

        createJButton1.setText("Delete Diet");
        createJButton1.setActionCommand("delete");
        createJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButton1ActionPerformed(evt);
            }
        });
        add(createJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, -1));

        jLabel9.setText("---------------------------------------------");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 344, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pic3.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel6.setPreferredSize(new java.awt.Dimension(600, 626));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        if(createJTextField.getText()=="" || stylePriceTxt.getText()=="")
        {return;}
        else{
        Diet hairstyle = enterprise.getFlavorDirectory().createFlavor();
        hairstyle.setName(createJTextField.getText());
        hairstyle.setPrice(Integer.parseInt(stylePriceTxt.getText()));
        hairstyle.setQuantity(0);}
        populateComboBox();
    }//GEN-LAST:event_createJButtonActionPerformed

    private void assignMaterialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMaterialBtnActionPerformed
        // TODO add your handling code here:
        Diet hairStyle = (Diet)styleCBox.getSelectedItem();
        AssignMaterialJPanel amjp = new AssignMaterialJPanel(userProcessContainer, hairStyle, enterprise, network);
        userProcessContainer.add("AssignMatirialJPanel", amjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_assignMaterialBtnActionPerformed

    private void styleCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleCBoxActionPerformed
        // TODO add your handling code here:
        Diet hairStyle = (Diet)styleCBox.getSelectedItem();
        if (hairStyle != null){
            populateMaterialTable(hairStyle);
        }
    }//GEN-LAST:event_styleCBoxActionPerformed

    private void assignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeBtnActionPerformed

        int selectedRow = processRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        DishRequest request = (DishRequest)processRequestJTable.getValueAt(selectedRow, 0);
        //request.setReceiver(userAccount);
        request.setReceiverEnterprise(enterprise);
        request.setStatus("Pending");
        populateProcessRequestTable();
    }//GEN-LAST:event_assignToMeBtnActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = processRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        DishRequest request = (DishRequest)processRequestJTable.getValueAt(selectedRow, 0);
        // Validate assignment
        if(request.getReceiverEnterprise()== null) {
            JOptionPane.showMessageDialog(null, "Please click \"Assign to me\" first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setStatus("Processing");

        ProcessDishJPanel processJPanel = new ProcessDishJPanel(userProcessContainer, userAccount, enterprise, network, request);
        userProcessContainer.add("processJPanel", processJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshSendBtnActionPerformed

        populateProcessRequestTable();
    }//GEN-LAST:event_refreshSendBtnActionPerformed

    private void accountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountJButtonActionPerformed
        // TODO add your handling code here:
        AccountJPanel accountJPanel = new AccountJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("processJPanel", accountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_accountJButtonActionPerformed

    private void createJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButton1ActionPerformed
         Diet hairStyle = (Diet)styleCBox.getSelectedItem();
         enterprise.getFlavorDirectory().getFlavorList().remove(hairStyle);
         populateComboBox();

         // TODO add your handling code here:
    }//GEN-LAST:event_createJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountJButton;
    private javax.swing.JButton assignMaterialBtn;
    private javax.swing.JButton assignToMeBtn;
    private javax.swing.JButton createJButton;
    private javax.swing.JButton createJButton1;
    private javax.swing.JTextField createJTextField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField hairQuantityTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable materialJTable;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable processRequestJTable;
    private javax.swing.JButton refreshSendBtn;
    private javax.swing.JComboBox styleCBox;
    private javax.swing.JTextField stylePriceTxt;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
