/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetDietician;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OnlineStoreEnterprise;
import Business.Food.Dish;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DishRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PhythonNo1
 */
public class ProcessDishJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NutritionDiningRoomEnterprise enterprise;
    private Network network;
    private DishRequest request;
    private UserAccount userAccount;
    /**
     * Creates new form ProcessHairJPanel
     */
    public ProcessDishJPanel(JPanel userProcessContainer, UserAccount userAccount,NutritionDiningRoomEnterprise enterprise, Network network, DishRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.request = request;
        this.userAccount = userAccount;
        
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        quantityTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sendJButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 142, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 223, -1, -1));
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 155, 66, -1));

        jLabel1.setText("Material:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 122, -1, -1));

        jLabel2.setText("Quantity:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 158, -1, -1));

        sendJButton.setText("Send");
        sendJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendJButtonActionPerformed(evt);
            }
        });
        add(sendJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 223, 86, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("Dish");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 119, 66, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pic3.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel7.setPreferredSize(new java.awt.Dimension(600, 626));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DieticianWorkAreaJPanel mwjp = (DieticianWorkAreaJPanel) component;
        mwjp.populateProcessRequestTable();
        mwjp.refreshHairQuantity();
        mwjp.refreshreduceCO2();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJButtonActionPerformed
        // TODO add your handling code here:
        try{Integer.parseInt(quantityTxt.getText());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The quantity is invalid.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        for(Dish hair : enterprise.getDishDirectory().getDishList()) {
            //if(material.getName().equals(materialCBox.getSelectedItem().toString())) {
            if(hair.getName().equals("dish")) {
                if(hair.getQuantity()-Integer.parseInt(quantityTxt.getText()) < 0) {
                    JOptionPane.showMessageDialog(null, "Dish Sample is insufficient.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                hair.setQuantity(hair.getQuantity()-Integer.parseInt(quantityTxt.getText()));
            }
        }   
        request.setStatus("Completed: "+quantityTxt.getText());
                
        // Send the sample to Online Store
        OnlineStoreEnterprise ent = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.equals(request.getSenderEnterprise())){
                ent = (OnlineStoreEnterprise) enterprise;
                break;
            }
        }
        if (ent != null){
            for(Dish hair : ent.getDishDirectory().getDishList()) {
                if(hair.getName().equals("dish")) {
                    hair.setQuantity(hair.getQuantity()+Integer.parseInt(quantityTxt.getText()));
            }
            }
        }  
        JOptionPane.showMessageDialog(null, "Reply and material sent successfully.", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_sendJButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton sendJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
