/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PythonNo1
 */
public class ManageAirlinersWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    public ManageAirlinersWorkAreaJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        populateTable();
        updateAirlinerBtn.setEnabled(false);
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) airlinerTbl.getModel();
        dtm.setRowCount(0);
        for (Airliner airliner: travelAgency.getAirlinerDir().getAirlinerList()) {
            Object[] row = new Object[3];
            row[0] = airliner;
            row[1] = airliner.getIataCode();
            try { row[2] = airliner.getFSCatalog().getFlightSchedule().size(); }
            catch (Exception e) {
                row[2] = "0"; }
            dtm.addRow(row);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAirlinerBtn = new javax.swing.JButton();
        searchAirlinerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerSearchTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        airlinerTbl = new javax.swing.JTable();
        airlinerNameTxt = new javax.swing.JTextField();
        iataCodeTxt = new javax.swing.JTextField();
        selectAirlinerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateAirlinerBtn = new javax.swing.JButton();
        manageFlightBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(154, 172, 145));

        createAirlinerBtn.setBackground(new java.awt.Color(186, 208, 208));
        createAirlinerBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createAirlinerBtn.setText("Create New Airliner");
        createAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerBtnActionPerformed(evt);
            }
        });

        searchAirlinerBtn.setBackground(new java.awt.Color(172, 206, 206));
        searchAirlinerBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        searchAirlinerBtn.setText("Search Airliners");
        searchAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAirlinerBtnActionPerformed(evt);
            }
        });

        airlinerSearchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "IATA Code", "Flight Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinerSearchTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Airliners Results");

        airlinerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "IATA Code", "Flight Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(airlinerTbl);

        selectAirlinerBtn.setBackground(new java.awt.Color(181, 213, 213));
        selectAirlinerBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        selectAirlinerBtn.setText("Select Airliner");
        selectAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAirlinerBtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Airliners:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IATA Code:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage Airliners");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("All Airliners");

        updateAirlinerBtn.setBackground(new java.awt.Color(0, 153, 153));
        updateAirlinerBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        updateAirlinerBtn.setText("Update AirLiners");
        updateAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirlinerBtnActionPerformed(evt);
            }
        });

        manageFlightBtn.setBackground(new java.awt.Color(185, 215, 215));
        manageFlightBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        manageFlightBtn.setText("Select and Manage Flights");
        manageFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFlightBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(198, 216, 216));
        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airlinerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(iataCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageFlightBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAirlinerBtn)
                    .addComponent(createAirlinerBtn))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airlinerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iataCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAirlinerBtn)
                    .addComponent(updateAirlinerBtn))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageFlightBtn)
                    .addComponent(backBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAirlinerBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) airlinerSearchTbl.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[3];
        for (Airliner airliner: travelAgency.getAirlinerDir().getAirlinerList()) {
            if(airlinerNameTxt.getText().equals(airliner.getAirlinerName()) || 
                    iataCodeTxt.getText().equals(airliner.getIataCode())) {
                row[0] = airliner;
                row[1] = airliner.getIataCode();
                try { row[2] = airliner.getFSCatalog().getFlightSchedule().size(); 
                //JOptionPane.showMessageDialog(null, "dubug test:refreshed");
                }
                catch (Exception e) {
                row[2] = "0"; }
                dtm.addRow(row);
            }
        }
        if(dtm.getRowCount() == 0)
            JOptionPane.showMessageDialog(null, "No Airliners found.");
        airlinerNameTxt.setText("");
        iataCodeTxt.setText("");
    }//GEN-LAST:event_searchAirlinerBtnActionPerformed

    private void createAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel panel = new CreateNewAirlinerJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("CreateNewAirlinersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_createAirlinerBtnActionPerformed

    private void manageFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFlightBtnActionPerformed
        // TODO add your handling code here:
        Airliner airliner;
        if (airlinerSearchTbl.getSelectedRow() == -1 && airlinerTbl.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (airlinerSearchTbl.getSelectedRow() != -1) {
            airliner = (Airliner)airlinerSearchTbl.getValueAt(airlinerSearchTbl.getSelectedRow(), 0);
        }
        else
            airliner = (Airliner)airlinerTbl.getValueAt(airlinerTbl.getSelectedRow(), 0);
        ManageFlightWorkAreaJPanel panel = new ManageFlightWorkAreaJPanel(userProcessContainer, travelAgency, airliner);
        userProcessContainer.add("ManageFlightWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageFlightBtnActionPerformed

    private void selectAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinerTbl.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            Airliner airliner = (Airliner)airlinerTbl.getValueAt(selectedRow, 0);
            airlinerNameTxt.setText(airliner.getAirlinerName());
            iataCodeTxt.setText(airliner.getIataCode());
        }
        updateAirlinerBtn.setEnabled(true);
    }//GEN-LAST:event_selectAirlinerBtnActionPerformed

    private void updateAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int listIndex = airlinerTbl.getSelectedRow();
        Airliner airliner = travelAgency.getAirlinerDir().getAirlinerList().get(listIndex);
        airliner.setAirlinerName(airlinerNameTxt.getText());
        airliner.setIataCode(iataCodeTxt.getText());
        populateTable();
        updateAirlinerBtn.setEnabled(false);
        airlinerNameTxt.setText("");
        iataCodeTxt.setText("");
    }//GEN-LAST:event_updateAirlinerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerNameTxt;
    private javax.swing.JTable airlinerSearchTbl;
    private javax.swing.JTable airlinerTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createAirlinerBtn;
    private javax.swing.JTextField iataCodeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton manageFlightBtn;
    private javax.swing.JButton searchAirlinerBtn;
    private javax.swing.JButton selectAirlinerBtn;
    private javax.swing.JButton updateAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
