/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetPurchasing;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Food.Material;
import Business.Network.Network;
import Business.Organization.NutritionPurchaseOrganization;
import Business.Organization.Organization;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaterialRequest;
import java.awt.Component;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PhythonNo1
 */
public class PurchaingRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NutritionDiningRoomEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form PurchaingRequestJPanel
     */
    public PurchaingRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, NutritionDiningRoomEnterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
        
        valueLabel.setText(enterprise.getName());
        // display combo items, based on suppliers
        materialCBox.removeAllItems();
        checkSuppliersMaterialList();
        for (Material material : checkSuppliersMaterialList()) {
            materialCBox.addItem(material);
        }
    }

    public ArrayList<Material> checkSuppliersMaterialList() {
        ArrayList<Material> suppliersMaterialList = new ArrayList<>();
                    
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof SupplierEnterprise){
                SupplierEnterprise ent = (SupplierEnterprise) enterprise;
                suppliersMaterialList.addAll(ent.getMaterialDirectory().getMaterialList());
            }
        }
        
        SortedSet<Material> templeteMaterialList = new TreeSet<Material>(new Comparator<Material>() {
            @Override
            public int compare(Material arg0, Material arg1) {
                return arg0.getName().compareTo(arg1.getName());
            }
        });        
        //And now if you insert a Person into your persons, the duplicates (based on their name property) will not be inserted.
   
        //So you can iterator over your list<Person> and insert every item of it into your persons set, 
        //and be sure that you will not have any duplicates. So the rest would be like:        
        Iterator<Material> iterator = suppliersMaterialList.iterator();
        while(iterator.hasNext()) {
            templeteMaterialList.add(iterator.next());
        }
        suppliersMaterialList.clear();
        suppliersMaterialList.addAll(templeteMaterialList); 
        //Now, your people does not contain duplicate names
        
        return suppliersMaterialList;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityTxt = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        requestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        materialCBox = new javax.swing.JComboBox();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 138, 83, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 195, -1, -1));

        requestJButton.setText("Request Material");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 195, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 53, 142, 30));

        materialCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        materialCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCBoxActionPerformed(evt);
            }
        });
        add(materialCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 105, 104, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 64, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Material:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 109, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Quantity:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 141, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Retail Price:   $");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        priceTxt.setEditable(false);
        add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pic5.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel7.setMinimumSize(new java.awt.Dimension(500, 629));
        jLabel7.setPreferredSize(new java.awt.Dimension(500, 626));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PurchasingWorkAreaJPanel pwjp = (PurchasingWorkAreaJPanel) component;
        pwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed

        try{Integer.parseInt(quantityTxt.getText());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The quantity is invalid.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Material material = (Material)materialCBox.getSelectedItem();
        int quantity = Integer.parseInt(quantityTxt.getText());

        MaterialRequest request = new MaterialRequest();
        request.setMaterial(material);
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setSenderEnterprise(enterprise);
        //request.setSenderOrganization(organization);
        request.setStatus("Sent");

        Organization org = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof FarmerOrganization){
                    org = organization;
                    break;
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Request sent successfully.", "Message", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_requestJButtonActionPerformed

    private void materialCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCBoxActionPerformed
        // TODO add your handling code here:
        Material selectedMaterial = (Material) materialCBox.getSelectedItem();
        priceTxt.setText(selectedMaterial.getPrice()+"");
    }//GEN-LAST:event_materialCBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox materialCBox;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton requestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
