/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SupplierFarmer;

import Business.Enterprise.SupplierEnterprise;
import Business.Food.Material;
import Business.Organization.SupplierPurchaseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaterialRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhythonNo1
 */
public class FarmerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private SupplierPurchaseOrganization organization;
    private SupplierEnterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new 
     * form FarmerWorkAreaJPanel
     */
    public FarmerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SupplierPurchaseOrganization organization, SupplierEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;

        valueLabel.setText(enterprise.getName()+", "+organization.getName());
        // Add all material in the Supplier
        if(enterprise.getMaterialDirectory().getMaterialList().isEmpty()) {
            for (Material.MaterialType type : Material.MaterialType.values()) {
                Material material = enterprise.getMaterialDirectory().createMaterial();
                material.setName(type.getValue());
                material.setQuantity(0);
                material.setPrice(type.getPrice());
            }
        }
        
        populateProcessRequestTable();
        populateInventoryTable();
    }

    public void populateProcessRequestTable() {
        DefaultTableModel model = (DefaultTableModel)processRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            int quantity = ((MaterialRequest) request).getQuantity();
            row[1] = quantity+"";
            row[2] = request.getSender().getEmployee().getName();
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    public void populateInventoryTable() {
        DefaultTableModel model = (DefaultTableModel)inventoryJTable.getModel();
        model.setRowCount(0);
        
        for (Material material : enterprise.getMaterialDirectory().getMaterialList()) {
            Object[] row = new Object[2];
            row[0] = material;
            row[1] = material.getQuantity();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        processJButton = new javax.swing.JButton();
        refreshSendBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        processRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        refreshInventoryBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryJTable = new javax.swing.JTable();
        addOneBtn = new javax.swing.JButton();
        deleteOneBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 142, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 230, -1));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        refreshSendBtn.setText("Refresh");
        refreshSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshSendBtnActionPerformed(evt);
            }
        });
        add(refreshSendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Process Request");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        processRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(processRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 390, 96));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier Inventory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        refreshInventoryBtn.setText("Refresh");
        refreshInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshInventoryBtnActionPerformed(evt);
            }
        });
        add(refreshInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        inventoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(inventoryJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 391, 97));

        addOneBtn.setText("+1");
        addOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneBtnActionPerformed(evt);
            }
        });
        add(addOneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 50, -1));

        deleteOneBtn.setText("-1");
        deleteOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOneBtnActionPerformed(evt);
            }
        });
        add(deleteOneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/14.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 626));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = processRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        MaterialRequest request = (MaterialRequest)processRequestJTable.getValueAt(selectedRow, 0);
        // Validate assignment
        if(request.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "Please click \"Assign to me\" first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setStatus("Processing");

        FarmerProcessJPanel processJPanel = new FarmerProcessJPanel(userProcessContainer, userAccount, enterprise, request);
        userProcessContainer.add("processJPanel", processJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshSendBtnActionPerformed

        populateProcessRequestTable();
    }//GEN-LAST:event_refreshSendBtnActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = processRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        MaterialRequest request = (MaterialRequest)processRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateProcessRequestTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshInventoryBtnActionPerformed
        // TODO add your handling code here:
        populateInventoryTable();
    }//GEN-LAST:event_refreshInventoryBtnActionPerformed

    private void addOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneBtnActionPerformed
        // TODO add your handling code here:
        int row = inventoryJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Material material = (Material)inventoryJTable.getValueAt(row, 0);
        material.setQuantity(material.getQuantity()+1);
    }//GEN-LAST:event_addOneBtnActionPerformed

    private void deleteOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOneBtnActionPerformed
        // TODO add your handling code here:
        int row = inventoryJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Material material = (Material)inventoryJTable.getValueAt(row, 0);
        if (material.getQuantity()== 0) {
            JOptionPane.showMessageDialog(null, "The amount is already 0.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        material.setQuantity(material.getQuantity()-1);
    }//GEN-LAST:event_deleteOneBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOneBtn;
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton deleteOneBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTable inventoryJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable processRequestJTable;
    private javax.swing.JButton refreshInventoryBtn;
    private javax.swing.JButton refreshSendBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
