/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetChef;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Food.Material;
import Business.Organization.ChefOrganization;
import Business.Organization.NutritionPurchaseOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaterialRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PhythonNo1
 */
public class ChefRequestMaterialJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ChefOrganization organization;
    private NutritionDiningRoomEnterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form BarberRequestMatirialJPanel
     */
    public ChefRequestMaterialJPanel(JPanel userProcessContainer, UserAccount account, ChefOrganization organization, NutritionDiningRoomEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        valueLabel.setText(enterprise.getName()+", "+organization.getName());
        // Add all material in the Gourmet
        if(enterprise.getMaterialDirectory().getMaterialList().isEmpty()) {
            for (Material.MaterialType type : Material.MaterialType.values()) {
                Material material = enterprise.getMaterialDirectory().createMaterial();
                material.setName(type.getValue());
                material.setPrice(type.getPrice());
            }
        }
        // Display combobox
        materialCBox.removeAllItems();
        for (Material material : enterprise.getMaterialDirectory().getMaterialList()) {
            materialCBox.addItem(material);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        requestMaterialJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        materialCBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Material:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantity:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 139, 78, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 204, -1, -1));

        requestMaterialJButton.setText("Request Material");
        requestMaterialJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMaterialJButtonActionPerformed(evt);
            }
        });
        add(requestMaterialJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 204, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 53, 142, 30));

        materialCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        materialCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCBoxActionPerformed(evt);
            }
        });
        add(materialCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 101, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel6.setPreferredSize(new java.awt.Dimension(600, 626));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChefWorkAreaJPanel cwjp = (ChefWorkAreaJPanel) component;
        cwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestMaterialJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMaterialJButtonActionPerformed
        // validate quantity
        try{Integer.parseInt(quantityTxt.getText());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The quantity is invalid.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Material material = (Material)materialCBox.getSelectedItem();
        int quantity = Integer.parseInt(quantityTxt.getText());

        MaterialRequest request = new MaterialRequest();
        request.setMaterial(material);
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setStatus("Sent");

        Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof NutritionPurchaseOrganization){
                    org = organization;
                    break;
                }
            }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

        JOptionPane.showMessageDialog(null, "Request sent successfully.", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_requestMaterialJButtonActionPerformed

    private void materialCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialCBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox materialCBox;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton requestMaterialJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
