/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GourmetChef;

import Business.Enterprise.NutritionDiningRoomEnterprise;
import Business.Food.Dish;
import Business.Food.Diet;
import Business.Food.Material;
import Business.WorkQueue.DietRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PhythonNo1
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NutritionDiningRoomEnterprise enterprise;
    private DietRequest request;
    /**
     * Creates new form ProcessWorkAreaJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, NutritionDiningRoomEnterprise enterprise, DietRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.request = request;
        
        valueLabel.setText(enterprise.getName());
        dishCBox.removeAllItems();
        for(Diet diet : enterprise.getFlavorDirectory().getFlavorList()) {
            dishCBox.addItem(diet);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doStyleBtn = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        dishCBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doStyleBtn.setText("Do Diet");
        doStyleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doStyleBtnActionPerformed(evt);
            }
        });
        add(doStyleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 191, -1, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 58, 158, 30));

        dishCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        dishCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishCBoxActionPerformed(evt);
            }
        });
        add(dishCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 128, 88, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Diet:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 124, 74, 26));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 189, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterpriseLabel.setText("Department :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 57, 142, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(911, 600));
        jLabel6.setPreferredSize(new java.awt.Dimension(600, 626));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void doStyleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doStyleBtnActionPerformed

        Diet diet = (Diet)dishCBox.getSelectedItem();
        // Valiadte the inventory
        for(Material materialNeed : diet.getMaterialDirectory().getMaterialList()) {
            for(Material materialHave : enterprise.getMaterialDirectory().getMaterialList()) {
                if (materialNeed.getName().equals(materialHave.getName()) && materialHave.getQuantity() - materialNeed.getQuantity()<0) {
                    int num = materialNeed.getQuantity()-materialHave.getQuantity() ;
                    JOptionPane.showMessageDialog(null, "The inventory is insufficient.Lacks "+materialNeed.getName()+" numbers of "+num, "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }

        request.setStatus("Completed");
//tritionDiningRoomEnterprise ent = (NutritionDiningRoomEnterprise) request.getReceiver();
        // Comsume material
        for(Material materialNeed : diet.getMaterialDirectory().getMaterialList()) {
            for(Material materialHave : enterprise.getMaterialDirectory().getMaterialList()) {
                if (materialNeed.getName().equals(materialHave.getName())) {
                    materialHave.setQuantity(materialHave.getQuantity() - materialNeed.getQuantity());
            }
            }
        }
        // Add Dish
        for(Dish dish : enterprise.getDishDirectory().getDishList()) {
            if(dish.getName().equals("dish")) {
                dish.setQuantity(dish.getQuantity()+1);
            }
        }
        // Add Diet count
        diet.setQuantity(diet.getQuantity()+1);
        JOptionPane.showMessageDialog(null, "Dish made successfully!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_doStyleBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChefWorkAreaJPanel cwjp = (ChefWorkAreaJPanel) component;
        cwjp.populateMakeDishTable();
        cwjp.populateInventoryTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void dishCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishCBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox dishCBox;
    private javax.swing.JButton doStyleBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
