/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SupplierPurchase;

import Business.Enterprise.SupplierEnterprise;
import Business.Food.Material;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PhythonNo1
 */
public class AddMaterialJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierEnterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form PurchaseWorkAreaJPanel
     */
    public AddMaterialJPanel(JPanel userProcessContainer, UserAccount userAccount,SupplierEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        materialNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Price:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));
        add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 38, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 120, 40));

        addJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 100, 40));

        enterpriseLabel.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        enterpriseLabel.setText("Add Matirials :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 350, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Material  Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        add(materialNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 82, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pic13.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel5.setPreferredSize(new java.awt.Dimension(800, 626));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PurchaseWorkAreaJPanel mwjp = (PurchaseWorkAreaJPanel) component;
        mwjp.populateInventoryTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        if (materialNameTxt.getText() == "") {
            JOptionPane.showMessageDialog(null, "The name can't be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{Integer.parseInt(priceTxt.getText());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The price is invalid.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Add material to itself
        Material material = enterprise.getMaterialDirectory().createMaterial();
        material.setName(materialNameTxt.getText());
        material.setPrice(Integer.parseInt(priceTxt.getText()));
        material.setQuantity(0);
        // Add material to barbershop, work done in barbershop      
        // JOptionPane validation
        JOptionPane.showMessageDialog(null, "Material added successfully.", "Message", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_addJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField materialNameTxt;
    private javax.swing.JTextField priceTxt;
    // End of variables declaration//GEN-END:variables
}
